### ISSUE TITLE
SDK 日志格式有问题

### ISSUE THREAD

**Issue by yusank** [ThinkingDataAnalytics/go-sdk#1]
通过 `logbus` 打日志时，如果日志类型为设置用户属性，则会报错。
原因：
- sdk 打的日志序列化后，必定带上 `#event_name`, 不管有没有值，导致`logbus` 检查日志格式时，报错 设置用户属性事件  不能带`#event_name`

解决方案：
```go
EventName  string                 `json:"#event_name, omitempty"`
```

**Comment by yusank** [comment]
json tag 后加上 不存在时忽略的标志 `omitempty`

**Comment by yusank** [comment]
希望能尽快更新

**Comment by ThinkingDataAnalytics** [comment]
这个问题在 v1.0.1 解掉了。请再 check 一下

**Comment by ThinkingDataAnalytics** [comment]
@yusank 这个问题刚刚更新了，v1.0.1

请再check 一下

**Comment by yusank** [comment]
解决了 ，感谢
