### ISSUE TITLE
LogBus是什么

### ISSUE THREAD

**Issue by weiwenwang** [ThinkingDataAnalytics/go-sdk#2]
sdk把数据写到本地文件之后， LogBus会把文件传输到服务器？LogBus是什么咋没介绍？

**Comment by xuzz1** [comment]
> sdk把数据写到本地文件之后， LogBus会把文件传输到服务器？LogBus是什么咋没介绍？

这个是详细介绍logbus的，你可以看一下https://doc.thinkingdata.cn/tdamanual/installation/logbus_installation.html，底层是flume实现的，flume把文件传输到服务器的
