### ISSUE TITLE
thinkingdata.New() 函数值只有一个返回值了，文档里面的代码有问题了。

### ISSUE THREAD

**Issue by Justxu** [ThinkingDataAnalytics/go-sdk#5]
这个是文档代码。
ta, err := thinkingdata.New(consumer)

这个是New 函数实现。
func New(c Consumer) TDAnalytics {
	return TDAnalytics{consumer: c,
		superProperties: make(map[string]interface{}),
		mutex:           new(sync.RWMutex)}
}

**Comment by sun16832** [comment]
是的。这里文档里没有更新
